sudo: true
services:
  - mysql
script:
  - sudo apt-get install -y sysbench
  - sysbench --test=oltp --oltp-table-size=1000000 --mysql-db=test --mysql-user=travis prepare
  - sysbench --test=oltp --oltp-table-size=1000000 --mysql-db=test --mysql-user=travis --max-time=60 --oltp-read-only=on --max-requests=0 --num-threads=8 run
